export const products = [
    {
        id: 1,
        name: "Dimsum Ayam",
        price: 18000,
        category: "Dimsum",
        image: "https://placehold.co/400x400/EAE0D5/3D2C1D?text=Dimsum+Ayam",
        description: "5 buah dimsum berisi daging ayam pilihan yang diolah dengan resep otentik. Cocok untuk camilan atau lauk.",
        featured: true,
        tags: ["New", "Best Seller"],
        allergens: ["Gandum"],
        rating: 4.8,
        reviewCount: 132,
        soldCount: 257,
        reviews: [
            { name: "Aditya P.", date: "10/09/2025", rating: 5, text: "Juara banget dimsum ayamnya! Dagingnya tebel dan sausnya pas." },
            { name: "Clarissa N.", date: "09/09/2025", rating: 5, text: "Selalu jadi andalan buat stok di kulkas. Anak-anak suka!" },
        ],
        isAvailable: true,
        currentStock: 100,
        stockHistory: [{ date: '2025-09-01', quantity: 100, type: 'initial' }],
    },
    {
        id: 2,
        name: "Dimsum Jamur",
        price: 18000,
        category: "Dimsum",
        image: "https://placehold.co/400x400/EAE0D5/3D2C1D?text=Dimsum+Jamur",
        description: "5 buah dimsum dengan isian jamur champignon segar. Pilihan lezat untuk Anda yang mencari varian non-daging.",
        featured: false,
        tags: ["New"],
        allergens: ["Gandum"],
        rating: 4.7,
        reviewCount: 110,
        soldCount: 215,
        reviews: [],
        isAvailable: true,
        currentStock: 100,
        stockHistory: [{ date: '2025-09-01', quantity: 100, type: 'initial' }],
    },
    {
        id: 3,
        name: "Dimsum Cumi",
        price: 18000,
        category: "Dimsum",
        image: "https://placehold.co/400x400/EAE0D5/3D2C1D?text=Dimsum+Cumi",
        description: "5 buah dimsum dengan isian cumi segar yang diolah sempurna, memberikan rasa gurih dan tekstur yang kenyal.",
        featured: false,
        tags: ["New"],
        allergens: ["Cumi", "Gandum"],
        rating: 4.6,
        reviewCount: 98,
        soldCount: 180,
        reviews: [],
        isAvailable: true,
        currentStock: 100,
        stockHistory: [{ date: '2025-09-01', quantity: 100, type: 'initial' }],
    },
    {
        id: 4,
        name: "Dimsum Udang",
        price: 18000,
        category: "Dimsum",
        image: "https://placehold.co/400x400/EAE0D5/3D2C1D?text=Dimsum+Udang",
        description: "4 buah dimsum hakau dengan isian udang utuh. Kulitnya transparan dan kenyal, membungkus udang segar yang manis.",
        featured: true,
        tags: ["New"],
        allergens: ["Udang", "Gandum"],
        rating: 4.9,
        reviewCount: 150,
        soldCount: 300,
        reviews: [
            { name: "Kevin A.", date: "11/09/2025", rating: 5, text: "Udangnya berasa banget, bukan kaleng-kaleng. Kulit hakaunya juga pas tipisnya." },
        ],
        isAvailable: true,
        currentStock: 100,
        stockHistory: [{ date: '2025-09-01', quantity: 100, type: 'initial' }],
    },
    {
        id: 5,
        name: "Dimsum Lunpia",
        price: 18000,
        category: "Dimsum",
        image: "https://placehold.co/400x400/EAE0D5/3D2C1D?text=Dimsum+Lunpia",
        description: "Perpaduan dimsum dan lumpia. 4 buah dimsum dengan isian rebung dan ayam, dibalut kulit tahu yang renyah.",
        featured: false,
        tags: ["New"],
        allergens: ["Kedelai"],
        rating: 4.5,
        reviewCount: 88,
        soldCount: 150,
        reviews: [],
        isAvailable: true,
        currentStock: 100,
        stockHistory: [{ date: '2025-09-01', quantity: 100, type: 'initial' }],
    },
    {
        id: 6,
        name: "Dimsum Mix 1",
        price: 20000,
        category: "Dimsum",
        image: "https://placehold.co/400x400/634832/FFFFFF?text=Dimsum+Mix",
        description: "Isi 4 buah dimsum campur berisi varian terlaris: Ayam, Jamur, Cumi, dan Udang. Pilihan praktis untuk mencoba semua rasa.",
        featured: true,
        tags: ["New", "Best Seller"],
        allergens: ["Cumi", "Udang", "Gandum"],
        rating: 5.0,
        reviewCount: 200,
        soldCount: 400,
        reviews: [
            { name: "Gabriella S.", date: "12/09/2025", rating: 5, text: "Suka banget sama paket mix ini, jadi bisa cobain semua rasa. Favoritku yang udang!" },
        ],
        isAvailable: true,
        currentStock: 100,
        stockHistory: [{ date: '2025-09-01', quantity: 100, type: 'initial' }],
    },
    {
        id: 7,
        name: "Dimsum Mix 2",
        price: 18000,
        category: "Dimsum",
        image: "https://placehold.co/400x400/634832/FFFFFF?text=Dimsum+Mix",
        description: "Kombinasi 4 buah dimsum berisi varian Ayam, Jamur, Cumi, dan Lunpia dalam satu sajian praktis.",
        featured: false,
        tags: ["New"],
        allergens: ["Cumi", "Gandum", "Kedelai"],
        rating: 4.8,
        reviewCount: 150,
        soldCount: 300,
        reviews: [],
        isAvailable: true,
        currentStock: 100,
        stockHistory: [{ date: '2025-09-01', quantity: 100, type: 'initial' }],
    },
    {
        id: 8,
        name: "Dimsum Mix 3",
        price: 18000,
        category: "Dimsum",
        image: "https://placehold.co/400x400/634832/FFFFFF?text=Dimsum+Mix",
        description: "Paket lengkap berisi 5 buah dimsum: Ayam, Jamur, Cumi, Udang, dan Lunpia. Paling lengkap untuk dinikmati bersama.",
        featured: false,
        tags: ["New"],
        allergens: ["Cumi", "Udang", "Gandum", "Kedelai"],
        rating: 4.9,
        reviewCount: 180,
        soldCount: 350,
        reviews: [],
        isAvailable: true,
        currentStock: 100,
        stockHistory: [{ date: '2025-09-01', quantity: 100, type: 'initial' }],
    },
    {
        id: 9,
        name: "Risol Beef Mayo",
        price: 15000,
        category: "Risol",
        image: "https://placehold.co/400x400/E67E22/FFFFFF?text=Risol",
        description: "5 buah risol dengan isian smoked beef premium dan saus mayones, dibalut kulit yang renyah saat digoreng.",
        featured: true,
        tags: ["New"],
        allergens: ["Daging Sapi", "Gandum", "Telur"],
        rating: 4.8,
        reviewCount: 120,
        soldCount: 250,
        reviews: [],
        isAvailable: true,
        currentStock: 100,
        stockHistory: [{ date: '2025-09-01', quantity: 100, type: 'initial' }],
    },
    {
        id: 10,
        name: "Nugget Ikan Tenggiri",
        price: 35000,
        category: "Nugget",
        image: "https://placehold.co/400x400/E67E22/FFFFFF?text=Nugget+Ikan",
        description: "10 buah nugget sehat dari daging ikan tenggiri segar. Gurih alami, kaya protein, dan tanpa bahan pengawet.",
        featured: false,
        tags: ["New"],
        allergens: ["Ikan", "Gandum", "Telur"],
        rating: 4.7,
        reviewCount: 100,
        soldCount: 200,
        reviews: [],
        isAvailable: true,
        currentStock: 100,
        stockHistory: [{ date: '2025-09-01', quantity: 100, type: 'initial' }],
    },
    {
        id: 11,
        name: "Nugget Ayam",
        price: 25000,
        category: "Nugget",
        image: "https://placehold.co/400x400/E67E22/FFFFFF?text=Nugget+Ayam",
        description: "10 buah nugget ayam homemade yang dibuat dari dada ayam fillet pilihan. Lebih padat, lebih juicy, dan lebih sehat.",
        featured: false,
        tags: ["New"],
        allergens: ["Gandum", "Telur"],
        rating: 4.8,
        reviewCount: 150,
        soldCount: 300,
        reviews: [],
        isAvailable: true,
        currentStock: 100,
        stockHistory: [{ date: '2025-09-01', quantity: 100, type: 'initial' }],
    },
    {
        id: 12,
        name: "Cireng Ayam Suwir",
        price: 20000,
        category: "Cireng",
        image: "https://placehold.co/400x400/EAE0D5/3D2C1D?text=Cireng",
        description: "5 buah cireng crispy dengan isian ayam suwir pedas. Perpaduan tekstur kenyal dan rasa pedas yang pas.",
        featured: false,
        tags: ["New"],
        allergens: [],
        rating: 4.6,
        reviewCount: 90,
        soldCount: 180,
        reviews: [],
        isAvailable: true,
        currentStock: 100,
        stockHistory: [{ date: '2025-09-01', quantity: 100, type: 'initial' }],
    },
    {
        id: 13,
        name: "Risol Ayam Suwir",
        price: 20000,
        category: "Risol",
        image: "https://placehold.co/400x400/E67E22/FFFFFF?text=Risol+Ayam",
        description: "5 buah risol klasik dengan isian ayam suwir dan sayuran, dimasak dengan bumbu spesial yang gurih.",
        featured: false,
        tags: ["New"],
        allergens: ["Gandum", "Telur"],
        rating: 4.7,
        reviewCount: 110,
        soldCount: 220,
        reviews: [],
        isAvailable: true,
        currentStock: 100,
        stockHistory: [{ date: '2025-09-01', quantity: 100, type: 'initial' }],
    },
    {
        id: 14,
        name: "Risol Ayam Bolognese",
        price: 20000,
        category: "Risol",
        image: "https://placehold.co/400x400/E67E22/FFFFFF?text=Risol+Bolognese",
        description: "5 buah risol dengan isian ayam cincang dan saus bolognese yang kaya rasa, dibalut kulit renyah.",
        featured: false,
        tags: ["New"],
        allergens: ["Gandum", "Telur"],
        rating: 4.8,
        reviewCount: 130,
        soldCount: 260,
        reviews: [],
        isAvailable: true,
        currentStock: 100,
        stockHistory: [{ date: '2025-09-01', quantity: 100, type: 'initial' }],
    },
    {
        id: 15,
        name: "Otak-Otak Bandeng",
        price: 22000,
        category: "Lauk",
        image: "https://placehold.co/400x400/EAE0D5/3D2C1D?text=Otak-Otak",
        description: "Satu ekor bandeng utuh tanpa duri, diisi adonan ikan dan bumbu rempah. Praktis dan lezat untuk lauk keluarga.",
        featured: true,
        tags: ["New"],
        allergens: ["Ikan", "Telur"],
        rating: 4.9,
        reviewCount: 180,
        soldCount: 360,
        reviews: [],
        isAvailable: true,
        currentStock: 100,
        stockHistory: [{ date: '2025-09-01', quantity: 100, type: 'initial' }],
    },
    {
        id: 16,
        name: "Pempek Ikan Tenggiri",
        price: 20000,
        category: "Pempek",
        image: "https://placehold.co/400x400/EAE0D5/3D2C1D?text=Pempek",
        description: "4 buah pempek lenjer dari ikan tenggiri asli, lengkap dengan kuah cuko pedas, manis, dan asam.",
        featured: false,
        tags: ["New"],
        allergens: ["Ikan"],
        rating: 4.8,
        reviewCount: 160,
        soldCount: 320,
        reviews: [],
        isAvailable: true,
        currentStock: 100,
        stockHistory: [{ date: '2025-09-01', quantity: 100, type: 'initial' }],
    },
    {
        id: 17,
        name: "Tahu Baso Sapi",
        price: 26000,
        category: "Lauk",
        image: "https://placehold.co/400x400/EAE0D5/3D2C1D?text=Tahu+Baso",
        description: "10 buah tahu lembut dengan isian bakso sapi yang padat dan kenyal. Cocok untuk lauk atau camilan.",
        featured: false,
        tags: ["New"],
        allergens: ["Daging Sapi", "Kedelai"],
        rating: 4.7,
        reviewCount: 140,
        soldCount: 280,
        reviews: [],
        isAvailable: true,
        currentStock: 100,
        stockHistory: [{ date: '2025-09-01', quantity: 100, type: 'initial' }],
    },
    {
        id: 18,
        name: "Sempolan Ayam",
        price: 20000,
        category: "Lauk",
        image: "https://placehold.co/400x400/EAE0D5/3D2C1D?text=Sempolan",
        description: "10 tusuk sempolan ayam yang gurih dan kenyal. Jajanan praktis yang tinggal digoreng dan dinikmati.",
        featured: false,
        tags: ["New"],
        allergens: ["Telur"],
        rating: 4.6,
        reviewCount: 120,
        soldCount: 240,
        reviews: [],
        isAvailable: true,
        currentStock: 100,
        stockHistory: [{ date: '2025-09-01', quantity: 100, type: 'initial' }],
    },
    {
        id: 19,
        name: "Gohyong",
        price: 35000,
        category: "Gohyong",
        image: "https://placehold.co/400x400/634832/FFFFFF?text=Gohyong",
        description: "Satu lonjor gohyong dengan isian ayam dan udang, dibalut kulit tahu yang renyah di luar dan juicy di dalam.",
        featured: true,
        tags: ["New", "Best Seller"],
        allergens: ["Udang", "Kedelai", "Telur"],
        rating: 5.0,
        reviewCount: 250,
        soldCount: 500,
        reviews: [
            { name: "Richard L.", date: "12/09/2025", rating: 5, text: "Gohyong terenak yang pernah saya coba. Isiannya full, kulitnya garing banget. 10/10!" },
        ],
        isAvailable: true,
        currentStock: 100,
        stockHistory: [{ date: '2025-09-01', quantity: 100, type: 'initial' }],
    },
    {
        id: 20,
        name: "Nugget Keju",
        price: 35000,
        category: "Nugget",
        image: "https://placehold.co/400x400/E67E22/FFFFFF?text=Nugget+Keju",
        description: "10 buah nugget ayam dengan isian keju cheddar premium yang meleleh saat digoreng. Favorit anak-anak dan dewasa.",
        featured: true,
        tags: ["New"],
        allergens: ["Keju", "Susu", "Gandum", "Telur"],
        rating: 4.9,
        reviewCount: 190,
        soldCount: 380,
        reviews: [],
        isAvailable: true,
        currentStock: 100,
        stockHistory: [{ date: '2025-09-01', quantity: 100, type: 'initial' }],
    },
    {
        id: 21,
        name: "Sosis Solo",
        price: 28000,
        category: "Lauk",
        image: "https://placehold.co/400x400/EAE0D5/3D2C1D?text=Sosis+Solo",
        description: "10 buah lumpia basah khas Solo dengan isian daging ayam cincang yang gurih. Lembut dan meleleh di mulut.",
        featured: false,
        tags: ["New"],
        allergens: ["Gandum", "Telur"],
        rating: 4.7,
        reviewCount: 130,
        soldCount: 260,
        reviews: [],
        isAvailable: true,
        currentStock: 100,
        stockHistory: [{ date: '2025-09-01', quantity: 100, type: 'initial' }],
    },
    {
        id: 22,
        name: "Gemblong Cotot",
        price: 15000,
        category: "Jajanan Pasar",
        image: "https://placehold.co/400x400/EAE0D5/3D2C1D?text=Gemblong",
        description: "12 buah gemblong ketan dengan isian gula merah yang lumer di mulut saat digigit. Jajanan tradisional yang manis dan legit.",
        featured: false,
        tags: ["New"],
        allergens: [],
        rating: 4.6,
        reviewCount: 110,
        soldCount: 220,
        reviews: [],
        isAvailable: true,
        currentStock: 100,
        stockHistory: [{ date: '2025-09-01', quantity: 100, type: 'initial' }],
    },
    {
        id: 23,
        name: "Gethuk Crispy",
        price: 15000,
        category: "Jajanan Pasar",
        image: "https://placehold.co/400x400/EAE0D5/3D2C1D?text=Gethuk",
        description: "12 buah gethuk singkong lembut dengan balutan tepung crispy yang renyah. Perpaduan rasa manis, gurih, dan renyah.",
        featured: false,
        tags: ["New"],
        allergens: ["Gandum"],
        rating: 4.5,
        reviewCount: 100,
        soldCount: 200,
        reviews: [],
        isAvailable: true,
        currentStock: 100,
        stockHistory: [{ date: '2025-09-01', quantity: 100, type: 'initial' }],
    },
    {
        id: 24,
        name: "Ubi Lumer",
        price: 15000,
        category: "Jajanan Pasar",
        image: "https://placehold.co/400x400/EAE0D5/3D2C1D?text=Ubi+Lumer",
        description: "12 buah bola-bola ubi ungu lembut dengan isian cokelat lumer. Camilan manis yang cocok untuk teman minum teh.",
        featured: false,
        tags: ["New"],
        allergens: [],
        rating: 4.7,
        reviewCount: 140,
        soldCount: 280,
        reviews: [],
        isAvailable: true,
        currentStock: 100,
        stockHistory: [{ date: '2025-09-01', quantity: 100, type: 'initial' }],
    },
    {
        id: 25,
        name: "Cireng Salju",
        price: 10000,
        category: "Cireng",
        image: "https://placehold.co/400x400/EAE0D5/3D2C1D?text=Cireng+Salju",
        description: "10 buah cireng original yang lembut di dalam dan garing di luar, disajikan dengan bumbu rujak pedas manis.",
        featured: false,
        tags: ["New"],
        allergens: [],
        rating: 4.4,
        reviewCount: 80,
        soldCount: 160,
        reviews: [],
        isAvailable: true,
        currentStock: 100,
        stockHistory: [{ date: '2025-09-01', quantity: 100, type: 'initial' }],
    },
    {
        id: 26,
        name: "Singkong Keju",
        price: 15000,
        category: "Jajanan Pasar",
        image: "https://placehold.co/400x400/EAE0D5/3D2C1D?text=Singkong+Keju",
        description: "Singkong pilihan yang empuk dan merekah, digoreng garing dan ditaburi keju parut melimpah.",
        featured: false,
        tags: ["New"],
        allergens: ["Keju", "Susu"],
        rating: 4.6,
        reviewCount: 120,
        soldCount: 240,
        reviews: [],
        isAvailable: true,
        currentStock: 100,
        stockHistory: [{ date: '2025-09-01', quantity: 100, type: 'initial' }],
    },
    {
        id: 27,
        name: "Kripik Kentang 220g",
        price: 25000,
        category: "Snack",
        image: "https://placehold.co/400x400/EAE0D5/3D2C1D?text=Kripik+Kentang",
        description: "Keripik kentang homemade super renyah dengan bumbu original gurih. Dibuat dari irisan tipis kentang asli. Kemasan 220g.",
        featured: false,
        tags: ["New"],
        allergens: [],
        rating: 4.8,
        reviewCount: 150,
        soldCount: 300,
        reviews: [],
        isAvailable: true,
        currentStock: 100,
        stockHistory: [{ date: '2025-09-01', quantity: 100, type: 'initial' }],
    },
    {
        id: 28,
        name: "Makaroni Ubi Ungu 250g",
        price: 25000,
        category: "Snack",
        image: "https://placehold.co/400x400/EAE0D5/3D2C1D?text=Makaroni",
        description: "Makaroni renyah dengan rasa manis alami dari ubi ungu asli. Snack unik dengan warna ungu yang cantik. Kemasan 250g.",
        featured: false,
        tags: ["New"],
        allergens: ["Gandum"],
        rating: 4.7,
        reviewCount: 130,
        soldCount: 260,
        reviews: [],
        isAvailable: true,
        currentStock: 100,
        stockHistory: [{ date: '2025-09-01', quantity: 100, type: 'initial' }],
    },
    {
        id: 29,
        name: "Makaroni Keju 250g",
        price: 40000,
        category: "Snack",
        image: "https://placehold.co/400x400/EAE0D5/3D2C1D?text=Makaroni+Keju",
        description: "Makaroni bantet renyah dengan balutan bumbu keju premium yang tebal. Rasa kejunya kuat dan gurih. Kemasan 250g.",
        featured: false,
        tags: ["New"],
        allergens: ["Gandum", "Keju", "Susu"],
        rating: 4.9,
        reviewCount: 180,
        soldCount: 360,
        reviews: [],
        isAvailable: true,
        currentStock: 100,
        stockHistory: [{ date: '2025-09-01', quantity: 100, type: 'initial' }],
    },
    {
        id: 30,
        name: "Makaroni Keju 500g",
        price: 65000,
        category: "Snack",
        image: "https://placehold.co/400x400/EAE0D5/3D2C1D?text=Makaroni+Keju",
        description: "Makaroni keju premium dalam kemasan jumbo 500g. Cocok untuk sharing atau stok camilan di rumah.",
        featured: true,
        tags: ["New", "Best Seller"],
        allergens: ["Gandum", "Keju", "Susu"],
        rating: 5.0,
        reviewCount: 220,
        soldCount: 440,
        reviews: [],
        isAvailable: true,
        currentStock: 100,
        stockHistory: [{ date: '2025-09-01', quantity: 100, type: 'initial' }],
    },
    {
        id: 31,
        name: "Ayam Ungkep",
        price: 80000,
        category: "Lauk",
        image: "https://placehold.co/400x400/EAE0D5/3D2C1D?text=Ayam+Ungkep",
        description: "Satu ekor ayam kampung utuh diungkep dengan bumbu kuning kaya rempah. Empuk dan bumbu meresap, tinggal goreng.",
        featured: true,
        tags: ["New"],
        allergens: [],
        rating: 4.9,
        reviewCount: 200,
        soldCount: 400,
        reviews: [],
        isAvailable: true,
        currentStock: 100,
        stockHistory: [{ date: '2025-09-01', quantity: 100, type: 'initial' }],
    },
    {
        id: 32,
        name: "Maryam Ori",
        price: 30000,
        category: "Maryam",
        image: "https://placehold.co/400x400/634832/FFFFFF?text=Maryam+Ori",
        description: "3 buah roti maryam original dengan tekstur lembut di dalam dan renyah di luar. Cocok dinikmati dengan aneka topping.",
        featured: false,
        tags: ["New"],
        allergens: ["Gandum"],
        rating: 4.7,
        reviewCount: 140,
        soldCount: 280,
        reviews: [],
        isAvailable: true,
        currentStock: 100,
        stockHistory: [{ date: '2025-09-01', quantity: 100, type: 'initial' }],
    },
    {
        id: 33,
        name: "Maryam Premium Cokelat",
        price: 35000,
        category: "Maryam",
        image: "https://placehold.co/400x400/634832/FFFFFF?text=Maryam+Cokelat",
        description: "3 buah roti maryam premium berisi lelehan cokelat belgia. Pilihan tepat untuk para pecinta cokelat.",
        featured: false,
        tags: ["New"],
        allergens: ["Gandum"],
        rating: 4.8,
        reviewCount: 160,
        soldCount: 320,
        reviews: [],
        isAvailable: true,
        currentStock: 100,
        stockHistory: [{ date: '2025-09-01', quantity: 100, type: 'initial' }],
    },
    {
        id: 34,
        name: "Maryam Premium Keju",
        price: 35000,
        category: "Maryam",
        image: "https://placehold.co/400x400/634832/FFFFFF?text=Maryam+Keju",
        description: "3 buah roti maryam lembut dengan isian keju cheddar parut yang gurih. Perpaduan rasa yang pas.",
        featured: false,
        tags: ["New"],
        allergens: ["Gandum", "Keju", "Susu"],
        rating: 4.9,
        reviewCount: 180,
        soldCount: 360,
        reviews: [],
        isAvailable: true,
        currentStock: 100,
        stockHistory: [{ date: '2025-09-01', quantity: 100, type: 'initial' }],
    },
    {
        id: 35,
        name: "Maryam Ayam Moza BBQ",
        price: 45000,
        category: "Maryam",
        image: "https://placehold.co/400x400/634832/FFFFFF?text=Maryam+BBQ",
        description: "2 buah roti maryam dengan isian ayam, saus BBQ, dan keju mozzarella. Sajian unik yang mengenyangkan.",
        featured: true,
        tags: ["New"],
        allergens: ["Gandum", "Keju", "Susu"],
        rating: 5.0,
        reviewCount: 210,
        soldCount: 420,
        reviews: [],
        isAvailable: true,
        currentStock: 100,
        stockHistory: [{ date: '2025-09-01', quantity: 100, type: 'initial' }],
    },
    {
        id: 36,
        name: "Maryam Carbonara",
        price: 45000,
        category: "Maryam",
        image: "https://placehold.co/400x400/634832/FFFFFF?text=Maryam+Carbonara",
        description: "2 buah roti maryam dengan isian smoked beef, saus carbonara, dan keju parmesan yang creamy.",
        featured: false,
        tags: ["New"],
        allergens: ["Gandum", "Keju", "Susu", "Daging Sapi"],
        rating: 4.9,
        reviewCount: 190,
        soldCount: 380,
        reviews: [],
        isAvailable: true,
        currentStock: 100,
        stockHistory: [{ date: '2025-09-01', quantity: 100, type: 'initial' }],
    },
    {
        id: 37,
        name: "Maryam Premium Red Velvet",
        price: 40000,
        category: "Maryam",
        image: "https://placehold.co/400x400/634832/FFFFFF?text=Maryam+Red+Velvet",
        description: "5 buah roti maryam dengan adonan red velvet dan isian cream cheese frosting yang manis dan sedikit asam.",
        featured: false,
        tags: ["New"],
        allergens: ["Gandum", "Susu"],
        rating: 4.8,
        reviewCount: 170,
        soldCount: 340,
        reviews: [],
        isAvailable: true,
        currentStock: 100,
        stockHistory: [{ date: '2025-09-01', quantity: 100, type: 'initial' }],
    },
    {
        id: 38,
        name: "Maryam Oreo",
        price: 35000,
        category: "Maryam",
        image: "https://placehold.co/400x400/634832/FFFFFF?text=Maryam+Oreo",
        description: "5 buah roti maryam lembut dengan taburan biskuit Oreo di setiap lapisannya. Manis dan renyah.",
        featured: false,
        tags: ["New"],
        allergens: ["Gandum"],
        rating: 4.7,
        reviewCount: 150,
        soldCount: 300,
        reviews: [],
        isAvailable: true,
        currentStock: 100,
        stockHistory: [{ date: '2025-09-01', quantity: 100, type: 'initial' }],
    },
    {
        id: 39,
        name: "Kebab Daging",
        price: 35000,
        category: "Kebab",
        image: "https://placehold.co/400x400/E67E22/FFFFFF?text=Kebab",
        description: "5 buah kebab ukuran reguler dengan isian daging sapi panggang, sayuran segar, dan saus spesial.",
        featured: true,
        tags: ["New"],
        allergens: ["Daging Sapi", "Gandum"],
        rating: 4.8,
        reviewCount: 180,
        soldCount: 360,
        reviews: [],
        isAvailable: true,
        currentStock: 100,
        stockHistory: [{ date: '2025-09-01', quantity: 100, type: 'initial' }],
    },
    {
        id: 40,
        name: "Kebab Daging Mini",
        price: 40000,
        category: "Kebab",
        image: "https://placehold.co/400x400/E67E22/FFFFFF?text=Kebab+Mini",
        description: "10 buah kebab mini dengan isian daging sapi panggang dan saus lezat. Ukuran pas untuk camilan atau acara.",
        featured: false,
        tags: ["New"],
        allergens: ["Daging Sapi", "Gandum"],
        rating: 4.7,
        reviewCount: 160,
        soldCount: 320,
        reviews: [],
        isAvailable: true,
        currentStock: 100,
        stockHistory: [{ date: '2025-09-01', quantity: 100, type: 'initial' }],
    },
    {
        id: 41,
        name: "Kebab Tuna",
        price: 35000,
        category: "Kebab",
        image: "https://placehold.co/400x400/E67E22/FFFFFF?text=Kebab+Tuna",
        description: "5 buah kebab dengan isian tuna mayo yang creamy dan lezat. Pilihan lebih sehat yang kaya protein.",
        featured: false,
        tags: ["New"],
        allergens: ["Ikan", "Gandum", "Telur"],
        rating: 4.6,
        reviewCount: 140,
        soldCount: 280,
        reviews: [],
        isAvailable: true,
        currentStock: 100,
        stockHistory: [{ date: '2025-09-01', quantity: 100, type: 'initial' }],
    },
    {
        id: 42,
        name: "Kebab Ayam",
        price: 35000,
        category: "Kebab",
        image: "https://placehold.co/400x400/E67E22/FFFFFF?text=Kebab+Ayam",
        description: "5 buah kebab dengan isian ayam panggang bumbu marinasi khas, dibalut tortilla lembut dan sayuran segar.",
        featured: false,
        tags: ["New"],
        allergens: ["Gandum"],
        rating: 4.7,
        reviewCount: 150,
        soldCount: 300,
        reviews: [],
        isAvailable: true,
        currentStock: 100,
        stockHistory: [{ date: '2025-09-01', quantity: 100, type: 'initial' }],
    },
    {
        id: 43,
        name: "Sambosa Daging",
        price: 35000,
        category: "Lainnya",
        image: "https://placehold.co/400x400/EAE0D5/3D2C1D?text=Sambosa",
        description: "6 buah sambosa renyah dengan isian daging sapi cincang dan bumbu kari yang aromatik. Camilan gurih khas Timur Tengah.",
        featured: false,
        tags: ["New"],
        allergens: ["Daging Sapi", "Gandum"],
        rating: 4.8,
        reviewCount: 170,
        soldCount: 340,
        reviews: [],
        isAvailable: true,
        currentStock: 100,
        stockHistory: [{ date: '2025-09-01', quantity: 100, type: 'initial' }],
    },
    {
        id: 44,
        name: "Donat Chocored",
        price: 35000,
        category: "Donat",
        image: "https://placehold.co/400x400/634832/FFFFFF?text=Donat",
        description: "5 buah donat kentang empuk dengan topping cokelat strawberry yang manis dan segar. Tampilannya cantik dan rasanya lezat.",
        featured: false,
        tags: ["New"],
        allergens: ["Gandum", "Susu", "Telur"],
        rating: 4.9,
        reviewCount: 190,
        soldCount: 380,
        reviews: [],
        isAvailable: true,
        currentStock: 100,
        stockHistory: [{ date: '2025-09-01', quantity: 100, type: 'initial' }],
    },
    {
        id: 45,
        name: "Chicken Wrap",
        price: 35000,
        category: "Lainnya",
        image: "https://placehold.co/400x400/EAE0D5/3D2C1D?text=Chicken+Wrap",
        description: "5 buah wrap berisi dada ayam fillet goreng crispy, sayuran segar, dan saus mayo, dibalut dalam tortilla lembut.",
        featured: false,
        tags: ["New"],
        allergens: ["Gandum", "Telur"],
        rating: 4.8,
        reviewCount: 160,
        soldCount: 320,
        reviews: [],
        isAvailable: true,
        currentStock: 100,
        stockHistory: [{ date: '2025-09-01', quantity: 100, type: 'initial' }],
    },
    {
        id: 46,
        name: "Sambosa Beef Moza",
        price: 35000,
        category: "Lainnya",
        image: "https://placehold.co/400x400/EAE0D5/3D2C1D?text=Sambosa+Moza",
        description: "6 buah sambosa dengan isian daging sapi cincang dan lelehan keju mozzarella yang melimpah.",
        featured: false,
        tags: ["New"],
        allergens: ["Daging Sapi", "Keju", "Susu", "Gandum"],
        rating: 4.9,
        reviewCount: 200,
        soldCount: 400,
        reviews: [],
        isAvailable: true,
        currentStock: 100,
        stockHistory: [{ date: '2025-09-01', quantity: 100, type: 'initial' }],
    },
    {
        id: 47,
        name: "Donat Original",
        price: 30000,
        category: "Donat",
        image: "https://placehold.co/400x400/634832/FFFFFF?text=Donat+Original",
        description: "10 buah donat kentang klasik yang super empuk dan ringan, ditaburi gula halus. Sederhana dan selalu jadi favorit.",
        featured: false,
        tags: ["New"],
        allergens: ["Gandum", "Susu", "Telur"],
        rating: 4.7,
        reviewCount: 150,
        soldCount: 300,
        reviews: [],
        isAvailable: true,
        currentStock: 100,
        stockHistory: [{ date: '2025-09-01', quantity: 100, type: 'initial' }],
    },
    {
        id: 48,
        name: "Pempek Lampung",
        price: 45000,
        category: "Pempek",
        image: "https://placehold.co/400x400/EAE0D5/3D2C1D?text=Pempek+Lampung",
        description: "10 buah pempek campur (lenjer dan adaan) khas Lampung dengan rasa ikan yang kuat dan cuko kental.",
        featured: true,
        tags: ["New", "Best Seller"],
        allergens: ["Ikan"],
        rating: 4.9,
        reviewCount: 250,
        soldCount: 500,
        reviews: [],
        isAvailable: true,
        currentStock: 100,
        stockHistory: [{ date: '2025-09-01', quantity: 100, type: 'initial' }],
    },
];